spring:
  application:
    name: Spring Boot and Camunda BPM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/camunda?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
    name:
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    #    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    show_sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
  liquibase:
    change-log: classpath:liquibase/master.xml

liquibase:


server:
  port: 8080

debug: true
